### ISSUE TITLE
[Feature]: Link a document in the content of NFT

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/archethic-wallet#32]
### Problem to solve

Put a menu to add documents (photo, video, etc..) to the blockchain in a NFT. For this I would like to create in the content with there name and initial supply, a mime type tag and the content of the document (in hex). This is so that when I read the ledger of the data of a transaction, I find the document and be able to reconstruct it for display in the application. 

### Solution

see the solution with @samuel-uniris

**Comment by samuel-uniris** [comment]
Hello.
Good idea.
Nothing prevent you to add some additional content in the NFT based transaction, as mime text or url of image, of hex encoded.

However I propose to put the image in the encrypted data so only the owner of the NFT can have the image (by leveraging authorized keys mechanism).

But if anyone have to see the image or a specimen you can put it in the content zone

**Comment by redDwarf03** [comment]
following the discussion with Samuel, stand by

**Comment by redDwarf03** [comment]
see https://github.com/archethic-foundation/aeip/blob/main/AEIP-2.md
