### ISSUE TITLE
Wallet Yubikey integration

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/archethic-wallet#7]

**Comment by lucy-sha512** [comment]
Hi @redDwarf03,
We need to integrate the our webauth client and server application into archethic wallet. It would be helpful;l if you could guide us into integrating libfido2 application with the Dart.

**Comment by redDwarf03** [comment]
Hello
Sure! How do you want to proceed?

**Comment by lucy-sha512** [comment]
@redDwarf03 for starters you have to give me a walkthrough of dart and integrating my libfido2 C library into it.
It would be better if we can set up a meet and discuss it in detail

**Comment by redDwarf03** [comment]
Can we exchange by telegram instead of github to organize us please (my telegram profile is @reddwarf03)
thx

**Comment by redDwarf03** [comment]
and for info: https://dart.dev/guides/libraries/c-interop
